### ISSUE TITLE
abstract and introduction

### ISSUE THREAD

**Issue by ivotron** [ivotron/popper2-paper#4]
a motivation section might also be needed that follows the introduction section

**Comment by qwofford** [comment]
I defended my thesis last Friday and turned in materials today, so I'm freeing up for work on this paper.

What is the publication target? Deadlines?

I ran this paper workflow today, and I'm planning to take a closer look at the details over the weekend.

**Comment by ivotron** [comment]
congrats @qwofford!!! that's a great achievement 🎉 🥂 

We haven't decided on a venue yet. Any suggestions? 

@JayjeetAtGithub is working now on the intro, and we have more or less the outline ready. We would really appreciate your feedback on it, specifically regarding the case studies we plan to include. Another section that we didn't include but I think we should is "Use Cases", where we generalize the distinct scenarios where Popper can be used, since the case studies won't cover all of them (e.g. CI, reproducible dev environments, automated performance regression testing, etc.).

Since this is an "introducing tool X" type of paper, we were wondering whether presenting case studies and use cases is enough, or if it would be necessary to have an experiment that shows the benefit of using Popper. what do you think?

Assuming we would need to run an experiment, we thought of using `time` as one metric, and setup an experiment where we ask subjects to follow instructions contained in a `README` file. We would divide subjects into three groups:
 1. `bare`. Instructions are from scratch, that is, they specify an expected OS (e.g. ubuntu) and instruct readers on what to install, and how to manually run a workflow once everything is installed.
 2.  `containerized`. Where we instruct the user to install docker, build containers and run the workflow manually. One variant could be to instruct users to pull already-built containers.
 3. `popperized`. Install docker and popper, then run the experiment.

The other experiment would be the same as above, but for creating a workflow. For this case we would provide functional scripts (e.g. in python), then ask the subjects to create a README with instructions on how to run the workflow, with a similar grouping.

So the above falls more on the UX or User Studies type of experiments, and we're not really experts in this, but we could give it a try. The more challenging thing is to control for distinct backgrounds, that is, some people is more familiar with bash, python, docker, automation, than others, so it's difficult to find a neutral baseline.

/cc @carlosmalt

**Comment by JayjeetAtGithub** [comment]
Hey @qwofford. Congratulations. 🎉
